language: cpp

os:
  - osx

compiler:
  - gcc

script:
  - ./UnitTest --enable-gcov && make && make check

before_install:
  - sudo pip install cpp-coveralls

install: make all

after_success:
  - coveralls --exclude lib --exclude tests --gcov-options '\-lp'
