language: cpp

compiler:
  - gcc

script:
  - ./UnitTest --enable-gcov && make && make check

before_install:
  - sudo pip install --user cpp-coveralls

install: make all

after_success:
  - coveralls --exclude lib --exclude tests --gcov-options '\-lp'
