TARGET_MAIN=main
TARGET_TEST=test
TARGET_REMOVE=rm
TARGET_ALL=all

FILE_MAIN=Main
FILE_TEST=UnitTest

CFLAGS= g++ -std=c++11
SU=sudo

$(TARGET_ALL): $(TARGET_REMOVE) $(TARGET_MAIN) $(TARGET_TEST)

$(TARGET_MAIN):
	$(SU) $(CFLAGS) $(FILE_MAIN).cpp -o $(FILE_MAIN)

$(TARGET_TEST):
	$(SU) $(CFLAGS) $(FILE_TEST).cpp -o $(FILE_TEST)

$(TARGET_REMOVE):
	$(SU) $(TARGET_REMOVE) -f $(FILE_MAIN)
	$(SU) $(TARGET_REMOVE) -f $(FILE_TEST)
