TARGET_MAIN=main
TARGET_TEST=test
TARGET_REMOVE=rm
TARGET_ALL=all

DIR_SRC=src/
DIR_INC=include/
DIR_TEST=tests/

FILE_SRC=Main
FILE_TEST=UnitTest

PATH_SRC=$(DIR_SRC)$(FILE_SRC)
PATH_TEST=$(DIR_TEST)$(FILE_TEST)

CFLAGS= g++ -std=c++11
SU=sudo

$(TARGET_ALL): $(TARGET_REMOVE) $(TARGET_MAIN) $(TARGET_TEST)

$(TARGET_MAIN):
	$(SU) $(CFLAGS) $(PATH_SRC).cpp -o $(FILE_SRC) -I$(DIR_INC)

$(TARGET_TEST):
	$(SU) $(CFLAGS) $(PATH_TEST).cpp -o $(FILE_TEST) -I$(DIR_INC)

$(TARGET_REMOVE):
	$(SU) $(TARGET_REMOVE) -f $(FILE_SRC)
	$(SU) $(TARGET_REMOVE) -f $(FILE_TEST)
